"use server";

import { createClient } from '@supabase/supabase-js';
import * as XLSX from 'xlsx';

export async function importDataBulkFormData(formData: FormData) {
    const tableName = formData.get('tableName') as string;
    const file = formData.get('file') as File;

    if (!tableName || !file) {
        return { success: false, error: "Parâmetros de importação em branco." };
    }

    try {
        const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
        const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
        
        if (!url || !key) {
            return { success: false, error: "Servidor mal configurado. Faltam as chaves mestras no ambiente real." };
        }

        const supabaseAdmin = createClient(url, key, {
            auth: {
                persistSession: false,
                autoRefreshToken: false,
                detectSessionInUrl: false,
            },
        });

        // 1. ArrayBuffer no Servidor Node.js
        const arrayBuffer = await file.arrayBuffer();
        
        // 2. O SheetJS processa melhor no backend com type: buffer em vez de array
        const wb = XLSX.read(Buffer.from(arrayBuffer), { type: "buffer" });

        if (!wb.SheetNames.length) {
            return { success: false, error: "Ficheiro sem folhas (sheets)." };
        }

        const wsname = wb.SheetNames[0];
        const ws = wb.Sheets[wsname];

        // 3. Parser JSON via raw falso, defval null.
        const rawData: any[] = XLSX.utils.sheet_to_json(ws, { defval: null, raw: false });

        if (rawData.length === 0) {
            return { success: false, error: "O Excel fornecido está completamente vazio." };
        }

        // Clean the objects (remove empty keys generated by empty columns like __EMPTY)
        const dataArray = rawData.map(row => {
            const newRow: any = {};
            for (const key in row) {
               if (!key || key.includes('__EMPTY')) continue;
               newRow[key.trim()] = typeof row[key] === 'string' ? row[key].trim() : row[key];
            }
            return newRow;
        });

        // 4. Upsert standard function with onConflict ID
        const { data, error } = await supabaseAdmin
            .from(tableName)
            .upsert(dataArray, { 
                onConflict: 'id', 
                ignoreDuplicates: false 
            })
            .select();

        if (error) {
            console.error(`PostgREST Import Data Error (${tableName}):`, error);
            // Formatar a mensagem RLS ou Violacao de Integridade Relacional de forma limpa
            let readableError = error.message;
            if (error.code === '23503') readableError = `Esta tabela precisa de relacionamentos prévios.\nPor favor insira as dependências base antes de inserir aqui. (${error.details})`;
            if (error.code === '23505') readableError = `Um ou mais registos já existem e não podem ser duplicados (${error.details})`;
            if (error.code === '42P01') readableError = `A tabela alvo "${tableName}" é inválida ou não existe.`;
            if (error.code === '22P02') readableError = `Existem dados nas células do Excel que não são suportados. (Ex: Letras onde deviam estar Números ou formatação errada). (${error.details})`;
            
            return {
                success: false,
                error: `Erro de Importação ("${tableName}"): ${readableError}`
            };
        }

        return {
            success: true,
            recordsAffected: dataArray.length,
            message: `Foram processados e inseridos ${dataArray.length} registos com sucesso.`
        };

    } catch (e: any) {
        console.error("Backend Server Error in importDataBulk:", e);
        return { success: false, error: `Falha interna no Servidor M.E.S: ${e.message}` };
    }
}
